# Generated by Django 2.1.7 on 2019-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190225_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
