# Generated by Django 2.1.7 on 2019-02-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190228_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
