# Generated by Django 3.0.1 on 2020-01-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200119_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmembership',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlistmembership',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Track'),
        ),
    ]
