# Generated by Django 3.0.7 on 2020-06-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file_path',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
