# Generated by Django 3.0.7 on 2020-06-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_track_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file_path',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
