# Generated by Django 3.0.7 on 2020-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200610_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file_path',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
