# Generated by Django 3.0.7 on 2020-06-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200610_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
