# Generated by Django 3.0.7 on 2020-11-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_art_path',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
