# Generated by Django 3.1.3 on 2020-11-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201109_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
    ]
